### ISSUE TITLE
Delete Branch After Merge

### ISSUE THREAD

**Issue by LibenHailu** [Ethiopian-Data-Science-Association/edsa-website#9]
**Description**

We would like to enable the "Delete branch after merge" feature for our repository to streamline our workflow and keep the branch list clean. This feature automatically deletes branches that have been merged into the main branch, reducing clutter and minimizing the risk of confusion with stale branches.

**Background**

Currently, after merging pull requests, branches remain in the repository. This can lead to a buildup of unused branches, making it difficult for contributors to find active branches and increasing the chances of mistakenly working on outdated branches.

**Proposed Solution**

1. Enable the "Delete branch after merge" setting in the repository settings.

2. Ensure that all team members are aware of this change and understand that branches will be automatically deleted after merging.

**Benefits**

- Improved Repository Management: Automatically deleting merged branches will help maintain a cleaner repository.
- Reduced Confusion: Contributors will have a clearer view of active branches, reducing the likelihood of errors.
- Streamlined Workflow: This change will simplify the process of managing branches, allowing developers to focus on active work.

**Steps to Implement**

1. Navigate to the repository settings.

2. Under the "Merge button" section, check the option for "Automatically delete head branches."

**Comment by brooksideas** [comment]
* I have taken a note of this matter , I have cleaned stale branches manually so far ; but I will enable this feature going forward. 

Done ! 
![image](https://github.com/user-attachments/assets/02932df2-050b-40ac-8034-0207321a2303)

Thank you.
